// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl80gwH8lB70-yqVIwDlBz8b2g0wdjusw',
    appId: '1:44504984963:web:ab57716c1be27fa0e89ab6',
    messagingSenderId: '44504984963',
    projectId: 'clone-414ac',
    authDomain: 'clone-414ac.firebaseapp.com',
    storageBucket: 'clone-414ac.firebasestorage.app',
    measurementId: 'G-8L3X8F2F7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYEPzAJvJr5MWG49R4S-KOJa4XNiCaXU',
    appId: '1:44504984963:android:bd7eaadb300a209fe89ab6',
    messagingSenderId: '44504984963',
    projectId: 'clone-414ac',
    storageBucket: 'clone-414ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZBcdy84C-TH-59ey83I-ME_dfzOoomU',
    appId: '1:44504984963:ios:54030d438f1bcc3ae89ab6',
    messagingSenderId: '44504984963',
    projectId: 'clone-414ac',
    storageBucket: 'clone-414ac.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZBcdy84C-TH-59ey83I-ME_dfzOoomU',
    appId: '1:44504984963:ios:54030d438f1bcc3ae89ab6',
    messagingSenderId: '44504984963',
    projectId: 'clone-414ac',
    storageBucket: 'clone-414ac.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl80gwH8lB70-yqVIwDlBz8b2g0wdjusw',
    appId: '1:44504984963:web:6fb2df76aa9e077de89ab6',
    messagingSenderId: '44504984963',
    projectId: 'clone-414ac',
    authDomain: 'clone-414ac.firebaseapp.com',
    storageBucket: 'clone-414ac.firebasestorage.app',
    measurementId: 'G-5MSEC6956J',
  );
}
